# Exported from Render
services:
- type: web
  name: To-Do-List_Backend-Node.Js_Desafio
  runtime: node
  repo: https://github.com/LaylaJHB/To-Do-List_Backend-Node.Js_Desafio
  plan: free
  envVars:
  - key: JWT_KEY
    sync: true
  - key: DB_USER
    sync: true
  - key: DB_PASS
    sync: true
  - key: DB_NAME
    sync: true
  - key: DB_HOST
    sync: true
  region: ohio
  buildCommand: npm install
  startCommand: npm run dev-prof-rodrigo
version: "1"
