//-----CADASTRAR USUÁRIO -------------/
POST http://localhost:3003/user/create 
Content-Type: application/json 

{
    "name": "Clementine Bauch",
    "email": "Nathan@yesenia.net",
    "password": "12345678910"
}


//PEGAR TODOS OS USUÁRIOS -------------/
###
GET  http://localhost:3003/user/getAll 



//CRIAR TAREFA --------------------- /
###
POST http://localhost:3003/task/create 
Content-Type: application/json 

{
    "id": "",
    "tilte": "Gerenciamento de tarefas",
    "description": "Atualizar o Trello com as novas demandas compartilhadas hoje",
    "deadline": "2023-09-06" ,
    "status": "concluída",
    "created_at": "2023-09-01",
    "authorId": "4c3497f6-502a-42fa-8e5e-c2450f4c284d" 
}


//BUSCAR TAREFA POR ID ------------------------------ /
###
GET  http://localhost:3003/task/searchPost/27255ea5-cc54-43b4-96f4-2bb73b7534a7



//BUSCAR TODAS AS TAREFAS ------------------------------ /
###
GET  http://localhost:3003/task/getAllPosts

