//-----CADASTRAR USUÁRIO -------------/
POST http://localhost:3003/user/create 
Content-Type: application/json 

{
    "name": "Fagundes Reis",
    "email": "fagundes@yesenia.net",
    "password": "1234567"
}


//PEGAR TODOS OS USUÁRIOS -------------/
###
GET  http://localhost:3003/user/getAll 


//LOGIN DO USUÁRIO -------------/
###
POST http://localhost:3003/user/login
Content-Type: application/json 

{
    "email": "jonas@yesenia.net",
    "password": "123456789"
}



//CRIAR TAREFA --------------------- /
###
POST http://localhost:3003/task/create 
Content-Type: application/json 

{
    "tilte": "Gerenciamento de tarefas",
    "description": "Atualizar o Trello com as novas demandas compartilhadas hoje",
    "deadline": "2023-09-06" ,
    "status": "pendente"
}


//BUSCAR TAREFA POR ID ------------------------------ /
###
GET  http://localhost:3003/task/searchPost/95ca708c-ae48-4dd0-820d-40cb20776b28



//BUSCAR TODAS AS TAREFAS ------------------------------ /
###
GET  http://localhost:3003/task/getAllPosts

//DELETAR TASK --------------------- /
###
DELETE  http://localhost:3003/task/deleteTaskById/95ca708c-ae48-4dd0-820d-40cb20776b28


//ATUALIZAR TAREFA --------------------- /
###
POST http://localhost:3003/task/updateTaskById/
Content-Type: application/json 

{
       
        "id": "d239a13d-9246-4351-b579-5d1c0aa81a36",
        "description": "Edição para Trello."

}