name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]          # <- Só funciona se o PR NÃO for de fork
    # se seus PRs vêm de fork, troque por:
    # pull_request_target:
    #   branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:                      # << secrets permitidos aqui
      JWT_KEY: ${{ secrets.JWT_KEY }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Verify secrets
        run: |
          echo "JWT_KEY=${JWT_KEY:-<empty>}"
          echo "JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-<empty>}"
          if [ -z "$JWT_KEY" ] || [ -z "$JWT_EXPIRES_IN" ]; then
            echo "❌ Secrets ausentes — verifique Settings > Secrets."
            exit 1
          fi

      - name: Install deps
        run: npm install

      - name: Run tests
        run: npm test
